<?php


/*
function chip_field_display_alter(&$display, $context) {
    dpm($display);
    dpm($context);
}
*/


/*
function chip_field_display_field_collection_item_alter(&$display, $context) {
    //dpm($display);
    dpm($context['field']['field_name']);
    dpm($context);
}
*/

/*
function chip_block_view_alter(&$data, $block) {
    dpm($data);
    dpm($block);
}
*/

function chip_user_presave(&$edit, $account, $category) {
    $edit['name'] = $edit['mail'];
}



